-- Vanilla mobility and stock armament from the official Barotrauma Wiki.
-- Loaded submarine files remain authoritative for class, tier, price and crew data.
return {
    azimuth = {
        horizontalSpeed = 25.9,
        descentSpeed = 17.1,
        weapons = { "2 Coilguns" },
        hardpoints = 1,
        other = { "2 Depth Charge Tubes" },
    },
    barsuk = {
        horizontalSpeed = 16.1,
        descentSpeed = 14.2,
        weapons = { "1 Coilgun", "1 Pulse Laser" },
        hardpoints = 1,
        other = { "1 Depth Charge Tube" },
    },
    berilia = {
        horizontalSpeed = 16.9,
        descentSpeed = 14.8,
        weapons = { "2 Coilguns", "1 Flak Cannon" },
        largeHardpoints = 1,
        other = { "2 Electrical Discharge Coils", "1 Depth Charge Tube" },
    },
    camel = {
        horizontalSpeed = 22.3,
        descentSpeed = 14.1,
        weapons = { "1 Coilgun", "1 Chaingun" },
        hardpoints = 1,
    },
    dugong = {
        horizontalSpeed = 21.6,
        descentSpeed = 13.6,
        weapons = { "2 Coilguns" },
        hardpoints = 1,
        other = { "1 Electrical Discharge Coil" },
    },
    herja = {
        horizontalSpeed = 22.1,
        descentSpeed = 15.3,
        weapons = { "1 Coilgun", "1 Chaingun", "1 Railgun" },
        hardpoints = 1,
        other = { "1 Electrical Discharge Coil", "1 Depth Charge Tube" },
    },
    humpback = {
        horizontalSpeed = 22.6,
        descentSpeed = 17.0,
        weapons = { "2 Coilguns", "1 Railgun" },
        hardpoints = 1,
    },
    kastrull = {
        horizontalSpeed = 20.6,
        descentSpeed = 8.5,
        weapons = { "2 Coilguns", "1 Railgun" },
        hardpoints = 1,
        other = { "2 Electrical Discharge Coils", "1 Depth Charge Tube", "Armed drone" },
    },
    orca = {
        horizontalSpeed = 24.8,
        descentSpeed = 16.8,
        weapons = { "2 Coilguns" },
        hardpoints = 1,
        other = { "1 Electrical Discharge Coil", "1 Depth Charge Tube" },
    },
    orca2 = {
        horizontalSpeed = 24.8,
        descentSpeed = 12.8,
        weapons = { "1 Chaingun", "1 Double Coilgun" },
        hardpoints = 1,
        other = { "1 Electrical Discharge Coil", "1 Depth Charge Tube" },
    },
    ["r-29"] = {
        horizontalSpeed = 18.7,
        descentSpeed = 9.9,
        weapons = { "1 Coilgun", "1 Flak Cannon" },
        hardpoints = 1,
        other = { "2 Electrical Discharge Coils" },
    },
    remora = {
        horizontalSpeed = 21.6,
        descentSpeed = 12.5,
        weapons = { "1 Coilgun", "1 Double Coilgun" },
        hardpoints = 1,
        other = { "1 Electrical Discharge Coil", "1 Depth Charge Tube", "Armed drone" },
    },
    typhon = {
        horizontalSpeed = 18.3,
        descentSpeed = 9.3,
        weapons = { "1 Coilgun", "1 Double Coilgun", "1 Railgun" },
        hardpoints = 1,
        other = { "1 Depth Charge Tube" },
    },
    typhon2 = {
        horizontalSpeed = 21.5,
        descentSpeed = 12.6,
        weapons = { "1 Chaingun", "2 Double Coilguns", "1 Railgun" },
        hardpoints = 1,
        other = { "1 Electrical Discharge Coil" },
    },
    wallaby = {
        horizontalSpeed = 23.4,
        descentSpeed = 15.5,
        weapons = { "2 Coilguns", "1 Railgun" },
        hardpoints = 1,
        other = { "1 Electrical Discharge Coil" },
    },
    winterhalter = {
        horizontalSpeed = 24.5,
        descentSpeed = 13.5,
        weapons = { "1 Coilgun", "1 Double Coilgun", "1 Railgun" },
        hardpoints = 1,
        other = { "1 Electrical Discharge Coil" },
    },
}
