#!/usr/bin/env python3
import html
import json
import re
import urllib.parse
import urllib.request
from pathlib import Path

API = "https://barotraumagame.com/baro-wiki/api.php"
ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "Lua" / "Client" / "wiring_tooltips.lua"


def request(parameters):
    url = API + "?" + urllib.parse.urlencode(parameters)
    request_object = urllib.request.Request(
        url,
        headers={"User-Agent": "JustEnoughBaro/1.0 (offline wiki data importer)"},
    )
    with urllib.request.urlopen(request_object, timeout=30) as response:
        return json.load(response)


def clean(fragment):
    value = re.sub(r"<[^>]+>", "", fragment, flags=re.S)
    return " ".join(html.unescape(value).split())


def table(page_html, class_name):
    match = re.search(
        rf'<table class="{re.escape(class_name)}">(.*?)</table>',
        page_html,
        re.S,
    )
    return match.group(1) if match else ""


def extract_side(page_html, label_table, tooltip_table, direction):
    labels = [
        clean(value)
        for value in re.findall(
            r'<div class="connectionpanel-(?:red|blue)label"><b>(.*?)</b></div>',
            table(page_html, label_table),
            re.S,
        )
    ]
    tooltips = [
        clean(value)
        for value in re.findall(
            r'<div class="cp-tooltip">(.*?)</div>',
            table(page_html, tooltip_table),
            re.S,
        )
    ]
    if len(labels) != len(tooltips):
        return []
    return [
        {"name": label, "direction": direction, "tooltip": tooltip}
        for label, tooltip in zip(labels, tooltips)
    ]


def lua_string(value):
    return "[=[" + value.replace("]=]", "] = ]") + "]=]"


def summary(page_html):
    quote = re.search(r"<blockquote>\s*<p>(.*?)</p>\s*</blockquote>", page_html, re.S)
    if quote:
        return clean(quote.group(1)).strip('"“”')
    return ""


pages = request(
    {
        "action": "query",
        "list": "embeddedin",
        "eititle": "Template:Connection panel",
        "einamespace": 0,
        "eilimit": 500,
        "format": "json",
    }
)["query"]["embeddedin"]

records = {}
for page in pages:
    title = page["title"]
    if "(Legacy)" in title or title in {"Wiring Components"}:
        continue
    parsed = request(
        {"action": "parse", "page": title, "prop": "text", "format": "json"}
    )
    page_html = parsed.get("parse", {}).get("text", {}).get("*", "")
    pins = extract_side(page_html, "connectionpanel-table1", "connectionpanel-table2", "input")
    pins += extract_side(page_html, "connectionpanel-table3", "connectionpanel-table4", "output")
    page_summary = summary(page_html)
    if pins or page_summary:
        key = re.sub(r"[^a-z0-9]", "", title.lower())
        records[key] = {"title": title, "summary": page_summary, "pins": pins}

# The consolidated page contains authoritative tooltips for several components
# whose individual pages render empty cp-tooltip nodes.
consolidated = request(
    {"action": "parse", "page": "Wiring Components", "prop": "text", "format": "json"}
).get("parse", {}).get("text", {}).get("*", "")
sections = re.split(r"(?=<h2>)", consolidated)
for section in sections:
    heading = re.search(r'<span class="mw-headline" id="([^"]+)"', section)
    if heading is None:
        continue
    title = clean(heading.group(1).replace("_", " "))
    pins = extract_side(section, "connectionpanel-table1", "connectionpanel-table2", "input")
    pins += extract_side(section, "connectionpanel-table3", "connectionpanel-table4", "output")
    section_summary = summary(section)
    if pins or section_summary:
        key = re.sub(r"[^a-z0-9]", "", title.lower())
        previous = records.get(key, {})
        records[key] = {
            "title": title,
            "summary": section_summary or previous.get("summary", ""),
            "pins": pins or previous.get("pins", []),
        }

lines = ["-- Generated by scripts/import_official_wiki_wiring.py", "return {"]
for key in sorted(records):
    record = records[key]
    lines.append(f"    [{json.dumps(key)}] = {{")
    lines.append(f"        title = {lua_string(record['title'])},")
    lines.append(f"        summary = {lua_string(record.get('summary', ''))},")
    lines.append("        pins = {")
    for pin in record["pins"]:
        lines.append(
            "            { name = %s, direction = %s, tooltip = %s },"
            % (
                lua_string(pin["name"]),
                lua_string(pin["direction"]),
                lua_string(pin["tooltip"]),
            )
        )
    lines.append("        },")
    lines.append("    },")
lines.append("}")
OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"Imported {len(records)} official connection panels into {OUTPUT}")
