// <auto-generated />
// Generated from the official Barotrauma Wiki ConnectionPanel tables by
// scripts/import_official_wiki_wiring.py. Blank descriptions are blank upstream.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text;

namespace JustEnoughBaro;

internal static class WiringDatabase
{
    private static readonly IReadOnlyDictionary<string, WiringPanelInfo> panels = CreatePanels();
    private static readonly IReadOnlyDictionary<string, string> aliases = CreateAliases();

    public static IReadOnlyDictionary<string, WiringPanelInfo> Panels => panels;
    public static IReadOnlyDictionary<string, string> Aliases => aliases;

    public static bool TryGet(string? prefabIdentifier, string? displayName, out WiringPanelInfo panel)
    {
        if (TryGet(prefabIdentifier, out panel)) { return true; }
        return TryGet(displayName, out panel);
    }

    public static bool TryGet(string? value, out WiringPanelInfo panel)
    {
        string key = NormalizeKey(value);
        if (panels.TryGetValue(key, out WiringPanelInfo? exact))
        {
            panel = exact;
            return true;
        }
        if (aliases.TryGetValue(key, out string? target) && panels.TryGetValue(target, out WiringPanelInfo? aliased))
        {
            panel = aliased;
            return true;
        }
        panel = null!;
        return false;
    }

    public static WiringPin? MatchPin(WiringPanelInfo panel, string pinName)
    {
        return MatchPin(panel, pinName, null);
    }

    public static WiringPin? MatchPin(WiringPanelInfo panel, string pinName, string? direction)
    {
        string key = NormalizeKey(pinName);
        foreach (WiringPin pin in panel.Pins)
        {
            if (NormalizeKey(pin.Name) != key) { continue; }
            if (string.IsNullOrWhiteSpace(direction) || string.Equals(pin.Direction, direction, StringComparison.OrdinalIgnoreCase))
            {
                return pin;
            }
        }
        return null;
    }

    public static string NormalizeKey(string? value)
    {
        if (string.IsNullOrWhiteSpace(value)) { return string.Empty; }
        StringBuilder result = new StringBuilder(value.Length);
        foreach (char character in value)
        {
            if (character is >= 'A' and <= 'Z') { result.Append((char)(character + 32)); }
            else if ((character >= 'a' && character <= 'z') || (character >= '0' && character <= '9')) { result.Append(character); }
        }
        return result.ToString();
    }

    private static IReadOnlyDictionary<string, WiringPanelInfo> CreatePanels()
    {
        return new Dictionary<string, WiringPanelInfo>(StringComparer.OrdinalIgnoreCase)
        {
            ["abscomponent"] = new WiringPanelInfo
            {
                Key = "abscomponent",
                Title = "Abs Component",
                Summary = "Outputs the absolute value of the input.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In", Direction = "input", Description = "" },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "" },
                }
            },
            ["acoscomponent"] = new WiringPanelInfo
            {
                Key = "acoscomponent",
                Title = "Acos Component",
                Summary = "Outputs the angle whose cosine is equal to the input.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In", Direction = "input", Description = "The input signal." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "The output of the component." },
                }
            },
            ["addercomponent"] = new WiringPanelInfo
            {
                Key = "addercomponent",
                Title = "Adder Component",
                Summary = "Outputs the sum of the received signals.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In_1", Direction = "input", Description = "First summand." },
                    new WiringPin { Name = "Signal_In_2", Direction = "input", Description = "Second summand." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "The sum of the summands." },
                }
            },
            ["alarmbuzzer"] = new WiringPanelInfo
            {
                Key = "alarmbuzzer",
                Title = "Alarm Buzzer",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Toggle_State", Direction = "input", Description = "Toggles between on and off when a signal of 1 is supplied." },
                    new WiringPin { Name = "Set_State", Direction = "input", Description = "Sets current state of alarm to 1(on) or 0(off)." },
                }
            },
            ["alienbutton"] = new WiringPanelInfo
            {
                Key = "alienbutton",
                Title = "Alien Button",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "signal_out", Direction = "output", Description = "Outputs a signal of 1 for one frame when pressed." },
                }
            },
            ["aliencoil"] = new WiringPanelInfo
            {
                Key = "aliencoil",
                Title = "Alien Coil",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Trigger_In", Direction = "input", Description = "Activates the device when a signal of 1 is supplied." },
                    new WiringPin { Name = "Shutdown", Direction = "input", Description = "Shuts the device down when a signal of 1 is supplied" },
                    new WiringPin { Name = "Power_In", Direction = "input", Description = "Power input for the device." },
                }
            },
            ["aliencurrentgenerator"] = new WiringPanelInfo
            {
                Key = "aliencurrentgenerator",
                Title = "Alien Current Generator",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "toggle_state", Direction = "input", Description = "Toggles sphere state on a non-zero signal." },
                    new WiringPin { Name = "set_state", Direction = "input", Description = "Sets the sphere active or inactive depending on the signal value (0 = inactive, non-zero = active)." },
                    new WiringPin { Name = "shutdown", Direction = "input", Description = "" },
                }
            },
            ["aliendoorshatches"] = new WiringPanelInfo
            {
                Key = "aliendoorshatches",
                Title = "Alien Doors & Hatches",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "toggle_state", Direction = "input", Description = "Toggles door state on a non-zero signal" },
                    new WiringPin { Name = "set_state", Direction = "input", Description = "Sets the door open or closed depending on the signal value (0 = closed, non-zero = open)." },
                    new WiringPin { Name = "state_out", Direction = "output", Description = "Sends a signal of 0 if the door is closed and 1 if the door is open." },
                }
            },
            ["aliengenerator"] = new WiringPanelInfo
            {
                Key = "aliengenerator",
                Title = "Alien Generator",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Shutdown", Direction = "input", Description = "Destroys an alien generator when it receives a non-zero and non-zero signal." },
                    new WiringPin { Name = "Power_Out", Direction = "output", Description = "Power output of the reactor." },
                }
            },
            ["alienmotionsensor"] = new WiringPanelInfo
            {
                Key = "alienmotionsensor",
                Title = "Alien Motion Sensor",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "toggle_state", Direction = "input", Description = "" },
                    new WiringPin { Name = "Shutdown", Direction = "input", Description = "" },
                    new WiringPin { Name = "set_state", Direction = "input", Description = "" },
                    new WiringPin { Name = "signal_out", Direction = "output", Description = "" },
                }
            },
            ["alienpump"] = new WiringPanelInfo
            {
                Key = "alienpump",
                Title = "Alien Pump",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Power_In", Direction = "input", Description = "Connecting a power source to this input will supply the pump with power." },
                    new WiringPin { Name = "Toggle_State", Direction = "input", Description = "Turns the pump on/off whenever a signal is received." },
                    new WiringPin { Name = "Set_State", Direction = "input", Description = "Turns the pump off when a signal \"0\" is received, and activates it when any other signal is received." },
                    new WiringPin { Name = "Set_Speed", Direction = "input", Description = "Sets the speed of the pump to the received value. The value is clamped between -100.0 and 100.0." },
                    new WiringPin { Name = "Set_Targetlevel", Direction = "input", Description = "Sets the target water level in the room to the received value, clamped between -100 and +100. -100 being 0% full. 0 being 50% full, and 100 being 100% full." },
                }
            },
            ["alienterminal"] = new WiringPanelInfo
            {
                Key = "alienterminal",
                Title = "Alien Terminal",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Shutdown", Direction = "input", Description = "Destroys an alien terminal when it receives a non-zero and non-zero signal" },
                    new WiringPin { Name = "signal_out_1", Direction = "output", Description = "Sends a signal of 1 when the blue/green button is pressed." },
                    new WiringPin { Name = "signal_out_2", Direction = "output", Description = "Sends a signal of 1 when the red button is pressed." },
                    new WiringPin { Name = "state_out", Direction = "output", Description = "" },
                }
            },
            ["alienturret"] = new WiringPanelInfo
            {
                Key = "alienturret",
                Title = "Alien Turret",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "power_in", Direction = "input", Description = "Power for firing the Alien Turret." },
                    new WiringPin { Name = "position_in", Direction = "input", Description = "Sets the firing angle of the Alien Turret (0-360)." },
                    new WiringPin { Name = "trigger_in", Direction = "input", Description = "Fires the Alien Turret when it receives a signal." },
                    new WiringPin { Name = "toggle_state", Direction = "input", Description = "" },
                    new WiringPin { Name = "set_state", Direction = "input", Description = "" },
                    new WiringPin { Name = "toggle_auto_operate", Direction = "input", Description = "" },
                    new WiringPin { Name = "set_auto_operate", Direction = "input", Description = "" },
                    new WiringPin { Name = "shutdown", Direction = "input", Description = "Destroys an Alien Turret when it receives a non-zero and non-zero signal" },
                }
            },
            ["andcomponent"] = new WiringPanelInfo
            {
                Key = "andcomponent",
                Title = "And Component",
                Summary = "Sends a signal when both inputs receive a signal within a set period of each other.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In_1", Direction = "input", Description = "The input of the first signal." },
                    new WiringPin { Name = "Signal_In_2", Direction = "input", Description = "The input of the second signal." },
                    new WiringPin { Name = "Set_Output", Direction = "input", Description = "Sets the \"true\" output." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "The output of the component." },
                }
            },
            ["asincomponent"] = new WiringPanelInfo
            {
                Key = "asincomponent",
                Title = "Asin Component",
                Summary = "Outputs the angle whose sine is equal to the input.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In", Direction = "input", Description = "The input signal." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "The output of the component." },
                }
            },
            ["atancomponent"] = new WiringPanelInfo
            {
                Key = "atancomponent",
                Title = "Atan Component",
                Summary = "Outputs the angle whose tangent is equal to the input. If the \"signal_in_x\" and \"signal_in_y\" connections are used, the input is interpreted as a vector and the angle calculated using Atan2.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In", Direction = "input", Description = "The input signal." },
                    new WiringPin { Name = "Signal_In_X", Direction = "input", Description = "The input of the X signal." },
                    new WiringPin { Name = "Signal_In_Y", Direction = "input", Description = "The input of the Y signal." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "The output of the component." },
                }
            },
            ["battery"] = new WiringPanelInfo
            {
                Key = "battery",
                Title = "Battery",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "power_in", Direction = "input", Description = "Stores inputted power in the battery." },
                    new WiringPin { Name = "set_charge_rate", Direction = "input", Description = "Sets the battery's charge rate to the inputted value." },
                    new WiringPin { Name = "disable_output", Direction = "input", Description = "Disables output after recieving a truthy signal. Enables output after receiving a falsey signal." },
                    new WiringPin { Name = "power_out", Direction = "output", Description = "Outputs battery's stored power to anything connected." },
                    new WiringPin { Name = "charge_out", Direction = "output", Description = "Outputs current amount of stored power." },
                    new WiringPin { Name = "charge_%", Direction = "output", Description = "Outputs percentage of the currently stored power." },
                    new WiringPin { Name = "charge_rate_out", Direction = "output", Description = "Outputs current charge rate." },
                    new WiringPin { Name = "condition_out", Direction = "output", Description = "Outputs the Battery's current condition. (0-100)" },
                    new WiringPin { Name = "load_value_out", Direction = "output", Description = "Outputs the Battery's load (required power)." },
                    new WiringPin { Name = "power_value_out", Direction = "output", Description = "Outputs the Battery's power (supplied power)." },
                }
            },
            ["button"] = new WiringPanelInfo
            {
                Key = "button",
                Title = "Button",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "Outputs a signal of 1 for one frame when pressed." },
                }
            },
            ["camera"] = new WiringPanelInfo
            {
                Key = "camera",
                Title = "Camera",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "control_in", Direction = "input", Description = "Controls the view." },
                }
            },
            ["ceilcomponent"] = new WiringPanelInfo
            {
                Key = "ceilcomponent",
                Title = "Ceil Component",
                Summary = "Transforms a given float input into the closest integer, rounding up.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In", Direction = "input", Description = "The input signal for the ceil operation." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "The result of the ceil operation." },
                }
            },
            ["chaingun"] = new WiringPanelInfo
            {
                Key = "chaingun",
                Title = "Chaingun",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Power_In", Direction = "input", Description = "Power for firing the Chaingun." },
                    new WiringPin { Name = "Position_In", Direction = "input", Description = "Sets the firing angle of the Chaingun (0-360)." },
                    new WiringPin { Name = "Trigger_In", Direction = "input", Description = "Fires the Chaingun when it receives a signal." },
                    new WiringPin { Name = "Toggle_Light", Direction = "input", Description = "Toggles the state of the Chaingun's light." },
                    new WiringPin { Name = "Set_Light", Direction = "input", Description = "Sets the state of the Chaingun's light." },
                    new WiringPin { Name = "Set_Auto_Operate", Direction = "input", Description = "Sets the state of the Chaingun's auto operation. Only works if it is allowed to auto operate with wiring." },
                    new WiringPin { Name = "Toggle_Auto_Operate", Direction = "input", Description = "Toggles the state of the Chaingun's auto operation. Only works if it is allowed to auto operate with wiring." },
                }
            },
            ["chaingunloader"] = new WiringPanelInfo
            {
                Key = "chaingunloader",
                Title = "Chaingun Loader",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "condition_out", Direction = "output", Description = "Outputs the Chaingun Loader's current condition. (0-100)" },
                    new WiringPin { Name = "ammunition_out", Direction = "output", Description = "Outputs the condition of the loaded ammunition box. (0-100)" },
                }
            },
            ["chargingdock"] = new WiringPanelInfo
            {
                Key = "chargingdock",
                Title = "Charging Dock",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "power_in", Direction = "input", Description = "Connecting a power source to this input will supply the Charging Dock with power." },
                }
            },
            ["circuitbox"] = new WiringPanelInfo
            {
                Key = "circuitbox",
                Title = "Circuit Box",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In_0", Direction = "input", Description = "" },
                    new WiringPin { Name = "Signal_In_1", Direction = "input", Description = "" },
                    new WiringPin { Name = "Signal_In_2", Direction = "input", Description = "" },
                    new WiringPin { Name = "Signal_In_3", Direction = "input", Description = "" },
                    new WiringPin { Name = "Signal_In_4", Direction = "input", Description = "" },
                    new WiringPin { Name = "Signal_In_5", Direction = "input", Description = "" },
                    new WiringPin { Name = "Signal_In_6", Direction = "input", Description = "" },
                    new WiringPin { Name = "Signal_In_7", Direction = "input", Description = "" },
                    new WiringPin { Name = "Signal_In_8", Direction = "input", Description = "" },
                    new WiringPin { Name = "Signal_In_9", Direction = "input", Description = "" },
                    new WiringPin { Name = "Signal_Out_0", Direction = "output", Description = "" },
                    new WiringPin { Name = "Signal_Out_1", Direction = "output", Description = "" },
                    new WiringPin { Name = "Signal_Out_2", Direction = "output", Description = "" },
                    new WiringPin { Name = "Signal_Out_3", Direction = "output", Description = "" },
                    new WiringPin { Name = "Signal_Out_4", Direction = "output", Description = "" },
                    new WiringPin { Name = "Signal_Out_5", Direction = "output", Description = "" },
                    new WiringPin { Name = "Signal_Out_6", Direction = "output", Description = "" },
                    new WiringPin { Name = "Signal_Out_7", Direction = "output", Description = "" },
                    new WiringPin { Name = "Signal_Out_8", Direction = "output", Description = "" },
                    new WiringPin { Name = "Signal_Out_9", Direction = "output", Description = "" },
                }
            },
            ["coilgun"] = new WiringPanelInfo
            {
                Key = "coilgun",
                Title = "Coilgun",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Power_In", Direction = "input", Description = "Power for firing the Coilgun." },
                    new WiringPin { Name = "Position_In", Direction = "input", Description = "Sets the firing angle of the Coilgun (0-360)." },
                    new WiringPin { Name = "Trigger_In", Direction = "input", Description = "Fires the Coilgun when it receives a signal." },
                    new WiringPin { Name = "Toggle_Light", Direction = "input", Description = "Toggles the state of the Coilgun's light." },
                    new WiringPin { Name = "Set_Light", Direction = "input", Description = "Sets the state of the Coilgun's light." },
                    new WiringPin { Name = "Set_Auto_Operate", Direction = "input", Description = "Sets the state of the Coilgun's auto operation. Only works if it is allowed to auto operate with wiring." },
                    new WiringPin { Name = "Toggle_Auto_Operate", Direction = "input", Description = "Toggles the state of the Coilgun's auto operation. Only works if it is allowed to auto operate with wiring." },
                }
            },
            ["coilgunloader"] = new WiringPanelInfo
            {
                Key = "coilgunloader",
                Title = "Coilgun Loader",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "condition_out", Direction = "output", Description = "Outputs the Coilgun Loader's current condition. (0-100)" },
                    new WiringPin { Name = "ammunition_out", Direction = "output", Description = "Outputs the condition of the loaded ammunition box. (0-100)" },
                }
            },
            ["colorcomponent"] = new WiringPanelInfo
            {
                Key = "colorcomponent",
                Title = "Color Component",
                Summary = "Outputs a combined color signal for light control.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_R", Direction = "input", Description = "The brightness of the red channel." },
                    new WiringPin { Name = "Signal_G", Direction = "input", Description = "The brightness of the green channel." },
                    new WiringPin { Name = "Signal_B", Direction = "input", Description = "The brightness of the blue channel." },
                    new WiringPin { Name = "Signal_A", Direction = "input", Description = "The transparency of the alpha channel." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "The combined color signal." },
                }
            },
            ["concatenationcomponent"] = new WiringPanelInfo
            {
                Key = "concatenationcomponent",
                Title = "Concatenation Component",
                Summary = "Joins the inputs together and outputs the joined value (for example, the inputs \"mud\" and \"raptor\" would output \"mudraptor\").",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In_1", Direction = "input", Description = "Input of the first signal." },
                    new WiringPin { Name = "Signal_In_2", Direction = "input", Description = "Input of the second signal." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "The joined value." },
                }
            },
            ["coscomponent"] = new WiringPanelInfo
            {
                Key = "coscomponent",
                Title = "Cos Component",
                Summary = "Outputs the cosine of the input.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In", Direction = "input", Description = "The input signal." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "The output of the component." },
                }
            },
            ["delaycomponent"] = new WiringPanelInfo
            {
                Key = "delaycomponent",
                Title = "Delay Component",
                Summary = "Delays all received signals for a specific amount of time.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In", Direction = "input", Description = "The signal to be delayed." },
                    new WiringPin { Name = "set_delay", Direction = "input", Description = "The delay duration, in seconds." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "The delayed signal." },
                }
            },
            ["depthchargeloader"] = new WiringPanelInfo
            {
                Key = "depthchargeloader",
                Title = "Depth Charge Loader",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "ammunition_out", Direction = "output", Description = "Outputs the amount of loaded depth charges. (0-1)" },
                }
            },
            ["depthchargetube"] = new WiringPanelInfo
            {
                Key = "depthchargetube",
                Title = "Depth Charge Tube",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Trigger_In", Direction = "input", Description = "Deploys the Depth Charge when it receives a signal." },
                }
            },
            ["detonator"] = new WiringPanelInfo
            {
                Key = "detonator",
                Title = "Detonator",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Activate", Direction = "input", Description = "When a signal is received activates detonator's payload." },
                }
            },
            ["dividecomponent"] = new WiringPanelInfo
            {
                Key = "dividecomponent",
                Title = "Divide Component",
                Summary = "Outputs the divided value of the received signals.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In_1", Direction = "input", Description = "The dividend (i.e. the number above the division line)." },
                    new WiringPin { Name = "Signal_In_2", Direction = "input", Description = "The divisor (i.e. the number below the division line)." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "The quotient (i.e. the result)." },
                }
            },
            ["dockinghatchport"] = new WiringPanelInfo
            {
                Key = "dockinghatchport",
                Title = "Docking Hatch & Port",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "toggle_state", Direction = "input", Description = "Docks/Undocks when a signal of 1 is supplied." },
                    new WiringPin { Name = "set_state", Direction = "input", Description = "Sets the state of the docking port (1=dock, 0=undock)" },
                    new WiringPin { Name = "Power", Direction = "output", Description = "Allows transfering power between the Submarine and whatever it is docked to." },
                    new WiringPin { Name = "state_out", Direction = "output", Description = "Sends the current state of the docking port (1=docked, 0=undocked)" },
                    new WiringPin { Name = "Proximity_Sensor", Direction = "output", Description = "Send a signal of 1 when the Docking Hatch is in range of an another Docking Hatch" },
                    new WiringPin { Name = "On_Dock", Direction = "output", Description = "Send a signal of 1 when the Docking Hatch docks" },
                    new WiringPin { Name = "On_Undock", Direction = "output", Description = "Send a signal of 1 when the Docking Hatch undocks" },
                }
            },
            ["doorshatches"] = new WiringPanelInfo
            {
                Key = "doorshatches",
                Title = "Doors & Hatches",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "toggle_state", Direction = "input", Description = "Toggles Hatch/Door's state between open and closed on a non-zero signal" },
                    new WiringPin { Name = "set_state", Direction = "input", Description = "Sets the Hatch/Door's open or closed depending on the signal value (0 = closed, non-zero = open)." },
                    new WiringPin { Name = "state_out", Direction = "output", Description = "Sends a signal of 0 if the Hatch/Door is closed and 1 if the door is open." },
                    new WiringPin { Name = "condition_out", Direction = "output", Description = "Outputs the Hatch/Door's current condition. (0-100)" },
                    new WiringPin { Name = "activate_out", Direction = "output", Description = "Sends a signal of 1 when the door/hatch or its buttons are pressed. Can be combined with the \"Toggle when clicked\" option to inhibit opening/closing." },
                }
            },
            ["doublecoilgun"] = new WiringPanelInfo
            {
                Key = "doublecoilgun",
                Title = "Double Coilgun",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Power_In", Direction = "input", Description = "Power for firing the Double Coilgun." },
                    new WiringPin { Name = "Position_In", Direction = "input", Description = "Sets the firing angle of the Double Coilgun (0-360)." },
                    new WiringPin { Name = "Trigger_In", Direction = "input", Description = "Fires the Double Coilgun when it receives a signal." },
                    new WiringPin { Name = "Toggle_Light", Direction = "input", Description = "Toggles the state of the Double Coilgun's light." },
                    new WiringPin { Name = "Set_Light", Direction = "input", Description = "Sets the state of the Double Coilgun's light." },
                    new WiringPin { Name = "Set_Auto_Operate", Direction = "input", Description = "Sets the state of the Double Coilgun's auto operation. Only works if it is allowed to auto operate with wiring." },
                    new WiringPin { Name = "Toggle_Auto_Operate", Direction = "input", Description = "Toggles the state of the Double Coilgun's auto operation. Only works if it is allowed to auto operate with wiring." },
                }
            },
            ["electricaldischargecoil"] = new WiringPanelInfo
            {
                Key = "electricaldischargecoil",
                Title = "Electrical Discharge Coil",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Power_In", Direction = "input", Description = "Power input for the device." },
                    new WiringPin { Name = "Trigger_In", Direction = "input", Description = "Activates the device when a signal of 1 is supplied." },
                }
            },
            ["emergencysiren"] = new WiringPanelInfo
            {
                Key = "emergencysiren",
                Title = "Emergency Siren",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Toggle_State", Direction = "input", Description = "Toggles between on and off when a signal of 1 is supplied." },
                    new WiringPin { Name = "Set_State", Direction = "input", Description = "Sets current state of alarm to 1(on) or 0(off)." },
                }
            },
            ["engines"] = new WiringPanelInfo
            {
                Key = "engines",
                Title = "Engines",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "power_in", Direction = "input", Description = "Connecting a power source to this input will supply the engine with power." },
                    new WiringPin { Name = "set_force", Direction = "input", Description = "Sets Engine force to the received value." },
                    new WiringPin { Name = "condition_out", Direction = "output", Description = "Outputs the Engine's current condition. (0-100)" },
                }
            },
            ["equalscomponent"] = new WiringPanelInfo
            {
                Key = "equalscomponent",
                Title = "Equals Component",
                Summary = "Sends a signal when both inputs receive the same signal.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In_1", Direction = "input", Description = "The input of the first signal." },
                    new WiringPin { Name = "Signal_In_2", Direction = "input", Description = "The input of the second signal." },
                    new WiringPin { Name = "set_output", Direction = "input", Description = "The input for setting the signal that will be output if the conditions are met." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "The output of the component." },
                }
            },
            ["exponentiationcomponent"] = new WiringPanelInfo
            {
                Key = "exponentiationcomponent",
                Title = "Exponentiation Component",
                Summary = "Outputs the input raised to a given power.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In", Direction = "input", Description = "The base to be used." },
                    new WiringPin { Name = "Set_Exponent", Direction = "input", Description = "The exponent to be used." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "The result of the exponentiation." },
                }
            },
            ["fabricatordeconstructor"] = new WiringPanelInfo
            {
                Key = "fabricatordeconstructor",
                Title = "Fabricator & Deconstructor",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "power_in", Direction = "input", Description = "Connecting a power source to this input will supply the Fabricator/Deconstructor with power." },
                    new WiringPin { Name = "condition_out", Direction = "output", Description = "Outputs the Fabricator/Deconstructor's current condition. (0-100)" },
                }
            },
            ["factorialcomponent"] = new WiringPanelInfo
            {
                Key = "factorialcomponent",
                Title = "Factorial Component",
                Summary = "Outputs the factorial of the input.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In", Direction = "input", Description = "Input signal for the factorial." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "The resulting factorial." },
                }
            },
            ["flakcannon"] = new WiringPanelInfo
            {
                Key = "flakcannon",
                Title = "Flak Cannon",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "power_in", Direction = "input", Description = "Power for firing the Flak Cannon." },
                    new WiringPin { Name = "position_in", Direction = "input", Description = "Signal input for aiming the Flak Cannon." },
                    new WiringPin { Name = "trigger_in", Direction = "input", Description = "Signal input for firing the Flak Cannon." },
                    new WiringPin { Name = "toggle_light", Direction = "input", Description = "Signal input for turning the Flak Cannon's light on/off." },
                    new WiringPin { Name = "set_light", Direction = "input", Description = "Signal input for setting the color of the Flak Cannon's light." },
                    new WiringPin { Name = "Set_Auto_Operate", Direction = "input", Description = "Sets the state of the Flak Cannon's auto operation. Only works if it is allowed to auto operate with wiring." },
                    new WiringPin { Name = "Toggle_Auto_Operate", Direction = "input", Description = "Toggles the state of the Flak Cannon's auto operation. Only works if it is allowed to auto operate with wiring." },
                }
            },
            ["flakcannonloader"] = new WiringPanelInfo
            {
                Key = "flakcannonloader",
                Title = "Flak Cannon Loader",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "condition_out", Direction = "output", Description = "Outputs the Flak Cannon Loader's current condition. (0-100)" },
                    new WiringPin { Name = "ammunition_out", Direction = "output", Description = "Outputs the condition of the loaded ammunition box. (0-100)" },
                }
            },
            ["floorcomponent"] = new WiringPanelInfo
            {
                Key = "floorcomponent",
                Title = "Floor Component",
                Summary = "Transforms a given float input into the closest integer, rounding down.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In", Direction = "input", Description = "The input signal for the floor operation." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "The result of the floor operation." },
                }
            },
            ["gravitysphere"] = new WiringPanelInfo
            {
                Key = "gravitysphere",
                Title = "Gravity Sphere",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "toggle_state", Direction = "input", Description = "Toggles sphere state on a non-zero signal." },
                    new WiringPin { Name = "set_state", Direction = "input", Description = "Sets the sphere active or inactive depending on the signal value (0 = inactive, non-zero = active)." },
                    new WiringPin { Name = "shutdown", Direction = "input", Description = "Breaks sphere on signal." },
                    new WiringPin { Name = "state_out", Direction = "output", Description = "Sends a signal of 1 if the sphere is active and 0 if it is inactive." },
                }
            },
            ["greatercomponent"] = new WiringPanelInfo
            {
                Key = "greatercomponent",
                Title = "Greater Component",
                Summary = "Sends a signal if the value the signal_in1 input is larger than the signal_in2 input.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In_1", Direction = "input", Description = "The input of the first signal." },
                    new WiringPin { Name = "Signal_In_2", Direction = "input", Description = "The input of the second signal." },
                    new WiringPin { Name = "set_output", Direction = "input", Description = "The input for setting the signal that will be output if the conditions are met." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "The output of the component." },
                }
            },
            ["guardianpod"] = new WiringPanelInfo
            {
                Key = "guardianpod",
                Title = "Guardian Pod",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "toggle", Direction = "input", Description = "" },
                    new WiringPin { Name = "set_state", Direction = "input", Description = "" },
                    new WiringPin { Name = "shutdown", Direction = "input", Description = "Destroys the Guardian Pod when it receives a non-null and non-zero signal" },
                    new WiringPin { Name = "state_out", Direction = "output", Description = "" },
                }
            },
            ["inputselectorcomponent"] = new WiringPanelInfo
            {
                Key = "inputselectorcomponent",
                Title = "Input Selector Component",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In_0", Direction = "input", Description = "First selectable signal." },
                    new WiringPin { Name = "Signal_In_1", Direction = "input", Description = "Second selectable signal." },
                    new WiringPin { Name = "Signal_In_2", Direction = "input", Description = "Third selectable signal." },
                    new WiringPin { Name = "Signal_In_3", Direction = "input", Description = "Fourth selectable signal." },
                    new WiringPin { Name = "Signal_In_4", Direction = "input", Description = "Fifth selectable signal." },
                    new WiringPin { Name = "Signal_In_5", Direction = "input", Description = "Sixth selectable signal." },
                    new WiringPin { Name = "Signal_In_6", Direction = "input", Description = "Seventh selectable signal." },
                    new WiringPin { Name = "Signal_In_7", Direction = "input", Description = "Eighth selectable signal." },
                    new WiringPin { Name = "Signal_In_8", Direction = "input", Description = "Ninth selectable signal." },
                    new WiringPin { Name = "Signal_In_9", Direction = "input", Description = "Tenth selectable signal." },
                    new WiringPin { Name = "Set_Input", Direction = "input", Description = "Selects specified input pin, starting from index 0, up to 9. Negative values and values above 9 are clamped to nearest index number." },
                    new WiringPin { Name = "Move_Input", Direction = "input", Description = "Moves from currently selected input index by the amount specified, essentially adding or subtracting the value from index. Also affected by component settings." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "Outputs signals incoming from selected input." },
                    new WiringPin { Name = "Selected_Input_Out", Direction = "output", Description = "Outputs current index of the selected input pin (e.g. SIGNAL_IN_4 is at index 4)." },
                }
            },
            ["junctionbox"] = new WiringPanelInfo
            {
                Key = "junctionbox",
                Title = "Junction Box",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "power", Direction = "output", Description = "Any devices that are wired to this output will draw their power from the reactor or batteries through the junction box." },
                    new WiringPin { Name = "signal_0", Direction = "output", Description = "Devices wired between this will send signal from one to each other." },
                    new WiringPin { Name = "signal_1", Direction = "output", Description = "Devices wired between this will send signal from one to each other." },
                    new WiringPin { Name = "signal_2", Direction = "output", Description = "Devices wired between this will send signal from one to each other." },
                    new WiringPin { Name = "signal_3", Direction = "output", Description = "Devices wired between this will send signal from one to each other." },
                    new WiringPin { Name = "condition_out", Direction = "output", Description = "Outputs the Junction Box's current condition. (0-100)" },
                    new WiringPin { Name = "power_value_out", Direction = "output", Description = "Outputs the Nuclear Reactor's current Power Output." },
                    new WiringPin { Name = "load_value_out", Direction = "output", Description = "Outputs the Ship's current Load." },
                }
            },
            ["largeturrethardpoint"] = new WiringPanelInfo
            {
                Key = "largeturrethardpoint",
                Title = "Large Turret Hardpoint",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Power_In", Direction = "input", Description = "Power for firing the weapon once installed." },
                    new WiringPin { Name = "Position_In", Direction = "input", Description = "Sets the firing angle of the weapon once installed (0-360)." },
                    new WiringPin { Name = "Trigger_In", Direction = "input", Description = "Fires the weapon when it receives a signal." },
                    new WiringPin { Name = "Toggle_Light", Direction = "input", Description = "Toggles the state of the weapon's light." },
                    new WiringPin { Name = "Set_Light", Direction = "input", Description = "Sets the state of the weapon's light." },
                }
            },
            ["lever"] = new WiringPanelInfo
            {
                Key = "lever",
                Title = "Lever",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "Toggles between a signal of 0 and 1 when pressed." },
                }
            },
            ["lightcomponent"] = new WiringPanelInfo
            {
                Key = "lightcomponent",
                Title = "Light Component",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Toggle_State", Direction = "input", Description = "Toggles between on and off when a signal of 1 is supplied." },
                    new WiringPin { Name = "Set_State", Direction = "input", Description = "Sets current state of component to 1(on) or 0(off)." },
                    new WiringPin { Name = "Set_Color", Direction = "input", Description = "Sets the color of the light." },
                }
            },
            ["medicalfabricator"] = new WiringPanelInfo
            {
                Key = "medicalfabricator",
                Title = "Medical Fabricator",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "power_in", Direction = "input", Description = "Connecting a power source to this input will supply the Medical Fabricator with power." },
                    new WiringPin { Name = "condition_out", Direction = "output", Description = "Outputs the Medical Fabricator's current condition. (0-100)" },
                }
            },
            ["memorycomponent"] = new WiringPanelInfo
            {
                Key = "memorycomponent",
                Title = "Memory Component",
                Summary = "Outputs a stored value that can be updated from other sources. Use the signal_in connection to set the stored value, and the lock_state input to toggle whether the received signals should be stored.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In", Direction = "input", Description = "The signal to be stored" },
                    new WiringPin { Name = "LOCK_STATE", Direction = "input", Description = "Sets whether signals will be stored (1=yes, 0=no)" },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "The currently stored signal" },
                }
            },
            ["modulocomponent"] = new WiringPanelInfo
            {
                Key = "modulocomponent",
                Title = "Modulo Component",
                Summary = "Outputs the remainder when the input is divided by a specific number.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In", Direction = "input", Description = "Dividend of the division." },
                    new WiringPin { Name = "Set_Modulus", Direction = "input", Description = "Divisor of the division." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "Remainder of the division." },
                }
            },
            ["motiondetector"] = new WiringPanelInfo
            {
                Key = "motiondetector",
                Title = "Motion Detector",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "State_Out", Direction = "output", Description = "Outputs a signal of 1 when a creature is detected, otherwise outputs 0." },
                }
            },
            ["multiplycomponent"] = new WiringPanelInfo
            {
                Key = "multiplycomponent",
                Title = "Multiply Component",
                Summary = "Outputs the product of the received signals.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In_1", Direction = "input", Description = "The first factor." },
                    new WiringPin { Name = "Signal_In_2", Direction = "input", Description = "The second factor." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "The resulting product." },
                }
            },
            ["navigationterminal"] = new WiringPanelInfo
            {
                Key = "navigationterminal",
                Title = "Navigation Terminal",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "power_in", Direction = "input", Description = "Connecting a power source to this input will supply the Navigation Terminal with power." },
                    new WiringPin { Name = "transducer_in", Direction = "input", Description = "Generates sonar. Must be set to use this." },
                    new WiringPin { Name = "velocity_in", Direction = "input", Description = "Allows remote velocity change in the form of [x velocity],[y velocity]" },
                    new WiringPin { Name = "velocity_x_out", Direction = "output", Description = "Connecting the engines to this output will allow the Navigation Terminal to control the engines thrust, allowing the submarine to move horizontally." },
                    new WiringPin { Name = "velocity_y_out", Direction = "output", Description = "Connecting the ballast pumps to this output will allow the Navigation Terminal to control the how much the ballast is filled, allowing the submarine to move vertically. This outputs -100 to 100 (adjusted by the neutral ballast value)." },
                    new WiringPin { Name = "signal_out_1", Direction = "output", Description = "Outputs a signal when the custom button is pressed on the Navigation Terminal GUI." },
                    new WiringPin { Name = "signal_out_2", Direction = "output", Description = "Outputs a signal when the custom button is pressed on the Navigation Terminal GUI. This is not present on the Shuttle Navigation Terminal." },
                    new WiringPin { Name = "signal_out_3", Direction = "output", Description = "Outputs a signal when the custom button is pressed on the Navigation Terminal GUI. This is not present on the Shuttle Navigation Terminal." },
                    new WiringPin { Name = "toggle_docking", Direction = "output", Description = "Outputs a signal when the docking button is pressed on the Navigation Terminal GUI." },
                    new WiringPin { Name = "current_velocity_x", Direction = "output", Description = "Outputs the current horizontal velocity." },
                    new WiringPin { Name = "current_velocity_y", Direction = "output", Description = "Outputs the current vertical velocity." },
                    new WiringPin { Name = "current_position_x", Direction = "output", Description = "Outputs the current horizontal position." },
                    new WiringPin { Name = "current_position_y", Direction = "output", Description = "Outputs the current vertical position." },
                    new WiringPin { Name = "condition_out", Direction = "output", Description = "Outputs the Navigation Terminal's current condition. (0-100)" },
                }
            },
            ["notcomponent"] = new WiringPanelInfo
            {
                Key = "notcomponent",
                Title = "Not Component",
                Summary = "Sends a signal when the input is NOT receiving a signal.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In", Direction = "input", Description = "The input signal." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "The output of the component." },
                }
            },
            ["nuclearreactor"] = new WiringPanelInfo
            {
                Key = "nuclearreactor",
                Title = "Nuclear Reactor",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "shutdown", Direction = "input", Description = "Turns the reactor off when it receives any signal." },
                    new WiringPin { Name = "set_fissionrate", Direction = "input", Description = "Sets fission rate to a fixed percentage (0-100)" },
                    new WiringPin { Name = "set_turbineoutput", Direction = "input", Description = "Sets turbine output to a fixed percentage (0-100)" },
                    new WiringPin { Name = "power_out", Direction = "output", Description = "Power output of the reactor (Limited to 1 Wire Connection)" },
                    new WiringPin { Name = "temperature_out", Direction = "output", Description = "Outputs the reactor's temperature (0-10000)." },
                    new WiringPin { Name = "meltdown_warning", Direction = "output", Description = "Outputs 1 when reactor's temperature is high (>6000)." },
                    new WiringPin { Name = "power_value_out", Direction = "output", Description = "Outputs the reactor's power output value." },
                    new WiringPin { Name = "load_value_out", Direction = "output", Description = "Outputs the reactor's load value." },
                    new WiringPin { Name = "fuel_out", Direction = "output", Description = "Outputs the sum of the the fuel rods Heat Potentials." },
                    new WiringPin { Name = "condition_out", Direction = "output", Description = "Outputs the Nuclear Reactor's Condition. (0-100)" },
                    new WiringPin { Name = "fuel_percentage_left", Direction = "output", Description = "Outputs the sum of the fuel rods percentage Conditions." },
                }
            },
            ["orcomponent"] = new WiringPanelInfo
            {
                Key = "orcomponent",
                Title = "Or Component",
                Summary = "Sends a signal if either of the inputs receives a signal.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In_1", Direction = "input", Description = "The input of the first signal." },
                    new WiringPin { Name = "Signal_In_2", Direction = "input", Description = "The input of the second signal." },
                    new WiringPin { Name = "Set_Output", Direction = "input", Description = "Sets the \"true\" output." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "The output of the component." },
                }
            },
            ["oscillatorcomponent"] = new WiringPanelInfo
            {
                Key = "oscillatorcomponent",
                Title = "Oscillator Component",
                Summary = "Sends out a periodic, oscillating signal.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Set_Frequency", Direction = "input", Description = "Sets the frequency of the oscillator, in Hz (Hertz)." },
                    new WiringPin { Name = "Set_Outputtype", Direction = "input", Description = "Sets the output type of the oscillator (0=pulse, 1=sine, 2=square)." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "The output of the component." },
                }
            },
            ["outputselectorcomponent"] = new WiringPanelInfo
            {
                Key = "outputselectorcomponent",
                Title = "Output Selector Component",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In", Direction = "input", Description = "The input signal." },
                    new WiringPin { Name = "Set_Output", Direction = "input", Description = "Selects specified output pin, starting from index 0, up to 9. Negative values and values above 9 are clamped to nearest index number." },
                    new WiringPin { Name = "Move_Output", Direction = "input", Description = "Moves from currently selected output index by the amount specified, essentially adding or subtracting the value from index. Also affected by component settings." },
                    new WiringPin { Name = "Signal_Out_0", Direction = "output", Description = "First selectable signal." },
                    new WiringPin { Name = "Signal_Out_1", Direction = "output", Description = "Second selectable signal." },
                    new WiringPin { Name = "Signal_Out_2", Direction = "output", Description = "Third selectable signal." },
                    new WiringPin { Name = "Signal_Out_3", Direction = "output", Description = "Fourth selectable signal." },
                    new WiringPin { Name = "Signal_Out_4", Direction = "output", Description = "Fifth selectable signal." },
                    new WiringPin { Name = "Signal_Out_5", Direction = "output", Description = "Sixth selectable signal." },
                    new WiringPin { Name = "Signal_Out_6", Direction = "output", Description = "Seventh selectable signal." },
                    new WiringPin { Name = "Signal_Out_7", Direction = "output", Description = "Eighth selectable signal." },
                    new WiringPin { Name = "Signal_Out_8", Direction = "output", Description = "Ninth selectable signal." },
                    new WiringPin { Name = "Signal_Out_9", Direction = "output", Description = "Tenth selectable signal." },
                    new WiringPin { Name = "Selected_Output_Out", Direction = "output", Description = "Outputs current index of the selected output pin (e.g. SIGNAL_OUT_4 is at index 4)." },
                }
            },
            ["oxygendetector"] = new WiringPanelInfo
            {
                Key = "oxygendetector",
                Title = "Oxygen Detector",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "Outputs the level of oxygen of the room it is in, ranging from 0 to 100." },
                    new WiringPin { Name = "Low_Oxygen", Direction = "output", Description = "Outputs a signal of 1 when the oxygen level is at or below 35, otherwise outputs 0." },
                }
            },
            ["oxygengenerator"] = new WiringPanelInfo
            {
                Key = "oxygengenerator",
                Title = "Oxygen Generator",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "power_in", Direction = "input", Description = "Connecting a power source to this input will supply the oxygen generator with power." },
                    new WiringPin { Name = "condition_out", Direction = "output", Description = "Outputs the Oxygen Generator's current condition. (0-100)" },
                }
            },
            ["periscope"] = new WiringPanelInfo
            {
                Key = "periscope",
                Title = "Periscope",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Position_Out", Direction = "output", Description = "A 0-360 value depending on the angle of the user's cursor from the center of their screen. Also switches the user's view to the connected installation's camera (if it has one)." },
                    new WiringPin { Name = "Trigger_Out", Direction = "output", Description = "Outputs a 1 when the user's \"Use\" key is pressed or held. Outputs nothing otherwise." },
                }
            },
            ["pipevalve"] = new WiringPanelInfo
            {
                Key = "pipevalve",
                Title = "Pipe Valve",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "signal_out", Direction = "output", Description = "Toggles between a signal of 0 and 1 depending on whether it's turned or not." },
                }
            },
            ["portablepump"] = new WiringPanelInfo
            {
                Key = "portablepump",
                Title = "Portable Pump",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "toggle_state", Direction = "input", Description = "Turns the pump on/off whenever a signal is received." },
                    new WiringPin { Name = "set_state", Direction = "input", Description = "Turns the pump off when a signal \"0\" is received, and activates it when any other signal is received." },
                    new WiringPin { Name = "set_speed", Direction = "input", Description = "Sets the speed of the pump to the received value. The value is clamped between -100.0 and 100.0." },
                    new WiringPin { Name = "set_targetlevel", Direction = "input", Description = "Sets the target water level in the room to the received value. This is clamped to the following limits: -50 meaning drain completely. 0 meaning fill to ½ . 50 meaning fill to full." },
                }
            },
            ["powerdistributor"] = new WiringPanelInfo
            {
                Key = "powerdistributor",
                Title = "Power Distributor",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "power_in", Direction = "input", Description = "Power input from a power network." },
                    new WiringPin { Name = "set_supply_ratio_0", Direction = "input", Description = "Sets the ratio of power to supply to POWER_OUT_0." },
                    new WiringPin { Name = "set_supply_ratio_1", Direction = "input", Description = "Sets the ratio of power to supply to POWER_OUT_1." },
                    new WiringPin { Name = "set_supply_ratio_2", Direction = "input", Description = "Sets the ratio of power to supply to POWER_OUT_2." },
                    new WiringPin { Name = "set_supply_ratio_3", Direction = "input", Description = "Sets the ratio of power to supply to POWER_OUT_3." },
                    new WiringPin { Name = "set_supply_ratio_4", Direction = "input", Description = "Sets the ratio of power to supply to POWER_OUT_4." },
                    new WiringPin { Name = "set_supply_ratio_5", Direction = "input", Description = "Sets the ratio of power to supply to POWER_OUT_5." },
                    new WiringPin { Name = "set_supply_ratio_6", Direction = "input", Description = "Sets the ratio of power to supply to POWER_OUT_6." },
                    new WiringPin { Name = "set_supply_ratio_7", Direction = "input", Description = "Sets the ratio of power to supply to POWER_OUT_7." },
                    new WiringPin { Name = "power_out_0", Direction = "output", Description = "Any devices wired to this output will draw their power from POWER_IN." },
                    new WiringPin { Name = "supply_ratio_out_0", Direction = "output", Description = "Outputs the current supply ratio for POWER_OUT_0." },
                    new WiringPin { Name = "power_out_1", Direction = "output", Description = "Any devices wired to this output will draw their power from POWER_IN." },
                    new WiringPin { Name = "supply_ratio_out_1", Direction = "output", Description = "Outputs the current supply ratio for POWER_OUT_1." },
                    new WiringPin { Name = "power_out_2", Direction = "output", Description = "Any devices wired to this output will draw their power from POWER_IN." },
                    new WiringPin { Name = "supply_ratio_out_2", Direction = "output", Description = "Outputs the current supply ratio for POWER_OUT_2." },
                    new WiringPin { Name = "power_out_3", Direction = "output", Description = "Any devices wired to this output will draw their power from POWER_IN." },
                    new WiringPin { Name = "supply_ratio_out_3", Direction = "output", Description = "Outputs the current supply ratio for POWER_OUT_3." },
                    new WiringPin { Name = "power_out_4", Direction = "output", Description = "Any devices wired to this output will draw their power from POWER_IN." },
                    new WiringPin { Name = "supply_ratio_out_4", Direction = "output", Description = "Outputs the current supply ratio for POWER_OUT_4." },
                    new WiringPin { Name = "power_out_5", Direction = "output", Description = "Any devices wired to this output will draw their power from POWER_IN." },
                    new WiringPin { Name = "supply_ratio_out_5", Direction = "output", Description = "Outputs the current supply ratio for POWER_OUT_5." },
                }
            },
            ["pulselaser"] = new WiringPanelInfo
            {
                Key = "pulselaser",
                Title = "Pulse Laser",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Power_In", Direction = "input", Description = "Power for firing the Pulse Laser." },
                    new WiringPin { Name = "Position_In", Direction = "input", Description = "Sets the firing angle of the Pulse Laser (0-360)." },
                    new WiringPin { Name = "Trigger_In", Direction = "input", Description = "Fires the Pulse Laser when it receives a signal." },
                    new WiringPin { Name = "Toggle_Light", Direction = "input", Description = "Toggles the state of the Pulse Laser's light." },
                    new WiringPin { Name = "Set_Light", Direction = "input", Description = "Sets the state of the Pulse Laser's light." },
                    new WiringPin { Name = "Set_Auto_Operate", Direction = "input", Description = "Sets the state of the Pulse Laser's auto operation. Only works if it is allowed to auto operate with wiring." },
                    new WiringPin { Name = "Toggle_Auto_Operate", Direction = "input", Description = "Toggles the state of the Pulse Laser's auto operation. Only works if it is allowed to auto operate with wiring." },
                }
            },
            ["pulselaserloader"] = new WiringPanelInfo
            {
                Key = "pulselaserloader",
                Title = "Pulse Laser Loader",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "condition_out", Direction = "output", Description = "Outputs the Pulse Laser Loader's current condition. (0-100)" },
                    new WiringPin { Name = "ammunition_out", Direction = "output", Description = "Outputs the condition of the loaded ammunition box. (0-100)" },
                }
            },
            ["pumps"] = new WiringPanelInfo
            {
                Key = "pumps",
                Title = "Pumps",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "power_in", Direction = "input", Description = "Connecting a power source to this input will supply the pump with power." },
                    new WiringPin { Name = "toggle_state", Direction = "input", Description = "Turns the pump on/off whenever a signal is received." },
                    new WiringPin { Name = "set_state", Direction = "input", Description = "Turns the pump off when a signal \"0\" is received, and activates it when any other signal is received." },
                    new WiringPin { Name = "set_speed", Direction = "input", Description = "Sets the speed of the pump to the received value. The value is clamped between -100.0 and 100.0." },
                    new WiringPin { Name = "set_targetlevel", Direction = "input", Description = "Sets the target water level in the room to the received value, clamped between -100 and +100. -100 being 0% full. 0 being 50% full, and 100 being 100% full." },
                    new WiringPin { Name = "condition_out", Direction = "output", Description = "Outputs the Pump's current condition. (0-100)" },
                }
            },
            ["railgun"] = new WiringPanelInfo
            {
                Key = "railgun",
                Title = "Railgun",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Power_In", Direction = "input", Description = "Power for firing the Railgun." },
                    new WiringPin { Name = "Position_In", Direction = "input", Description = "Sets the firing angle of the Railgun (0-360)." },
                    new WiringPin { Name = "Trigger_In", Direction = "input", Description = "Fires the Railgun when it receives a signal." },
                    new WiringPin { Name = "Toggle_Light", Direction = "input", Description = "Toggles the state of the Railgun's light." },
                    new WiringPin { Name = "Set_Light", Direction = "input", Description = "Sets the state of the Railgun's light." },
                    new WiringPin { Name = "Set_Auto_Operate", Direction = "input", Description = "Sets the state of the Railgun's auto operation. Only works if it is allowed to auto operate with wiring." },
                    new WiringPin { Name = "Toggle_Auto_Operate", Direction = "input", Description = "Toggles the state of the Railgun's auto operation. Only works if it is allowed to auto operate with wiring." },
                }
            },
            ["railgunloader"] = new WiringPanelInfo
            {
                Key = "railgunloader",
                Title = "Railgun Loader",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "condition_out", Direction = "output", Description = "Outputs the Railgun Loader's current condition. (0-100)" },
                    new WiringPin { Name = "ammunition_out", Direction = "output", Description = "Outputs the amount of loaded shells. (0-6)" },
                }
            },
            ["regexfindcomponent"] = new WiringPanelInfo
            {
                Key = "regexfindcomponent",
                Title = "RegEx Find Component",
                Summary = "Sends a signal if the received signal matches a specific regular expression pattern.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In", Direction = "input", Description = "The input signal." },
                    new WiringPin { Name = "set_output", Direction = "input", Description = "The input for setting the signal that will be output if the conditions are met." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "The output of the component." },
                }
            },
            ["relaycomponent"] = new WiringPanelInfo
            {
                Key = "relaycomponent",
                Title = "Relay Component",
                Summary = "When switched on, forwards all received signals from the input connections to the outputs.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Power_In", Direction = "input", Description = "Power input from a power network." },
                    new WiringPin { Name = "Signal_In_1", Direction = "input", Description = "The input of the first signal." },
                    new WiringPin { Name = "Signal_In_2", Direction = "input", Description = "The input of the second signal." },
                    new WiringPin { Name = "Signal_In_3", Direction = "input", Description = "The input of the third signal." },
                    new WiringPin { Name = "Signal_In_4", Direction = "input", Description = "The input of the fourth signal." },
                    new WiringPin { Name = "Signal_In_5", Direction = "input", Description = "The input of the fifth signal." },
                    new WiringPin { Name = "Toggle_State", Direction = "input", Description = "Toggles the state on any signal." },
                    new WiringPin { Name = "Set_State", Direction = "input", Description = "Sets the state of the Relay. (0 = Off, all other signals = On)" },
                    new WiringPin { Name = "Power_Out", Direction = "output", Description = "Power output to a power network." },
                    new WiringPin { Name = "Signal_Out_1", Direction = "output", Description = "The output of the first signal." },
                    new WiringPin { Name = "Signal_Out_2", Direction = "output", Description = "The output of the second signal." },
                    new WiringPin { Name = "Signal_Out_3", Direction = "output", Description = "The output of the third signal." },
                    new WiringPin { Name = "Signal_Out_4", Direction = "output", Description = "The output of the fourth signal." },
                    new WiringPin { Name = "Signal_Out_5", Direction = "output", Description = "The output of the fifth signal." },
                    new WiringPin { Name = "State_Out", Direction = "output", Description = "The current state of the relay." },
                    new WiringPin { Name = "Load_Value_Out", Direction = "output", Description = "Outputs the current load level as a number (required power)." },
                    new WiringPin { Name = "Power_Value_Out", Direction = "output", Description = "Outputs the current power level as a number (supplied power)." },
                }
            },
            ["researchstation"] = new WiringPanelInfo
            {
                Key = "researchstation",
                Title = "Research Station",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "power_in", Direction = "input", Description = "Connecting a power source to this input will supply the Research Station with power." },
                    new WiringPin { Name = "condition_out", Direction = "output", Description = "Outputs the Research Station's current condition. (0-100)" },
                }
            },
            ["roundcomponent"] = new WiringPanelInfo
            {
                Key = "roundcomponent",
                Title = "Round Component",
                Summary = "Rounds a numerical input to the nearest integer value.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In", Direction = "input", Description = "Input signal to be rounded." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "The rounded output signal." },
                }
            },
            ["searchlight"] = new WiringPanelInfo
            {
                Key = "searchlight",
                Title = "Searchlight",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "toggle_state", Direction = "input", Description = "Toggles light on/off when an input of 1 is received." },
                    new WiringPin { Name = "power_in", Direction = "input", Description = "Provides power to the Searchlight." },
                    new WiringPin { Name = "position_in", Direction = "input", Description = "Controls where the Searchlight is aiming." },
                    new WiringPin { Name = "set_light", Direction = "input", Description = "Sets light to on (1) or off (0), when a continuous signal is received." },
                }
            },
            ["signalcheckcomponent"] = new WiringPanelInfo
            {
                Key = "signalcheckcomponent",
                Title = "Signal Check Component",
                Summary = "Sends a signal when a signal matching a specific value is received.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In", Direction = "input", Description = "The input signal." },
                    new WiringPin { Name = "Set_Output", Direction = "input", Description = "Sets the \"true\" output." },
                    new WiringPin { Name = "Set_Targetsignal", Direction = "input", Description = "Sets the signal that must be matched to." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "The output of the component." },
                }
            },
            ["sincomponent"] = new WiringPanelInfo
            {
                Key = "sincomponent",
                Title = "Sin Component",
                Summary = "Outputs the sine of the input.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In", Direction = "input", Description = "The input signal." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "The output of the component." },
                }
            },
            ["smokedetector"] = new WiringPanelInfo
            {
                Key = "smokedetector",
                Title = "Smoke Detector",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "Outputs a signal of 1 when fire is detected, otherwise outputs 0." },
                }
            },
            ["sonarmonitor"] = new WiringPanelInfo
            {
                Key = "sonarmonitor",
                Title = "Sonar Monitor",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "power_in", Direction = "input", Description = "Connecting a power source to this input will supply the Sonar Monitor with power." },
                    new WiringPin { Name = "transducer_in", Direction = "input", Description = "Allows the generation of sonar. Must be set to allow usage." },
                    new WiringPin { Name = "condition_out", Direction = "output", Description = "Outputs the Sonar Monitor's current condition. (0-100)" },
                }
            },
            ["sonartransducer"] = new WiringPanelInfo
            {
                Key = "sonartransducer",
                Title = "Sonar Transducer",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "power_in", Direction = "input", Description = "Connecting a power source to this input will supply the Sonar Monitor with power." },
                    new WiringPin { Name = "data_out", Direction = "output", Description = "Sends out sonar." },
                }
            },
            ["squarerootcomponent"] = new WiringPanelInfo
            {
                Key = "squarerootcomponent",
                Title = "Square Root Component",
                Summary = "Outputs the square root of the input.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In", Direction = "input", Description = "The input of the component." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "The output of the component." },
                }
            },
            ["statusmonitor"] = new WiringPanelInfo
            {
                Key = "statusmonitor",
                Title = "Status Monitor",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "power_in", Direction = "input", Description = "Connecting a power source to this input will supply the Status Monitor with power." },
                    new WiringPin { Name = "water_data_in", Direction = "input", Description = "Connecting a water detector's signal output to this input will give the Status Monitor information about water level in area where detector is placed." },
                    new WiringPin { Name = "oxygen_data_in", Direction = "input", Description = "Connecting an oxygen detector’s signal output to this input will give the Status Monitor information about oxygen quality in area where detector is placed." },
                    new WiringPin { Name = "condition_out", Direction = "output", Description = "Outputs the current condition of the status monitor, from 0 to 100." },
                }
            },
            ["subtractcomponent"] = new WiringPanelInfo
            {
                Key = "subtractcomponent",
                Title = "Subtract Component",
                Summary = "Outputs the subtracted value of the received signals.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In_1", Direction = "input", Description = "The minuend (value to the left of the minus sign)." },
                    new WiringPin { Name = "Signal_In_2", Direction = "input", Description = "The subtrahend (value to the right of the minus sign)." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "The resulting difference." },
                }
            },
            ["supercapacitor"] = new WiringPanelInfo
            {
                Key = "supercapacitor",
                Title = "Supercapacitor",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "power_in", Direction = "input", Description = "Stores inputted power in the supercapacitor." },
                    new WiringPin { Name = "set_charge_rate", Direction = "input", Description = "Sets the supercapacitor's charge rate to the inputted value." },
                    new WiringPin { Name = "disable_output", Direction = "input", Description = "Disables output after recieving a truthy signal. Enables output after receiving a falsey signal." },
                    new WiringPin { Name = "power_out", Direction = "output", Description = "Outputs supercapacitor's stored power to anything connected." },
                    new WiringPin { Name = "charge_out", Direction = "output", Description = "Outputs current amount of stored power." },
                    new WiringPin { Name = "charge_%", Direction = "output", Description = "Outputs percentage of the currently stored power." },
                    new WiringPin { Name = "charge_rate_out", Direction = "output", Description = "Outputs current charge rate." },
                    new WiringPin { Name = "condition_out", Direction = "output", Description = "Outputs the Supercapacitor's current condition. (0-100)" },
                    new WiringPin { Name = "load_value_out", Direction = "output", Description = "Outputs the Supercapacitor's load (required power)." },
                    new WiringPin { Name = "power_value_out", Direction = "output", Description = "Outputs the Supercapacitor's power (supplied power)." },
                }
            },
            ["surveillancecamera"] = new WiringPanelInfo
            {
                Key = "surveillancecamera",
                Title = "Surveillance Camera",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "control_in", Direction = "input", Description = "Controls the view." },
                }
            },
            ["surveillancecenter"] = new WiringPanelInfo
            {
                Key = "surveillancecenter",
                Title = "Surveillance Center",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "POWER_IN", Direction = "input", Description = "Connecting a power source to this input will supply the Surveillance Center with power." },
                    new WiringPin { Name = "CONDITION_OUT", Direction = "output", Description = "Outputs the Surveillance Center's current condition. (0-100)" },
                    new WiringPin { Name = "POSITION_OUT", Direction = "output", Description = "" },
                    new WiringPin { Name = "TRIGGER_OUT", Direction = "output", Description = "" },
                    new WiringPin { Name = "PREV_CAMERA", Direction = "output", Description = "" },
                    new WiringPin { Name = "NEXT_CAMERA", Direction = "output", Description = "" },
                }
            },
            ["switch"] = new WiringPanelInfo
            {
                Key = "switch",
                Title = "Switch",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "Toggles between a signal of 0 and 1 when pressed." },
                }
            },
            ["tancomponent"] = new WiringPanelInfo
            {
                Key = "tancomponent",
                Title = "Tan Component",
                Summary = "Outputs the tangent of the input.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In", Direction = "input", Description = "The input signal." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "The output of the component." },
                }
            },
            ["terminal"] = new WiringPanelInfo
            {
                Key = "terminal",
                Title = "Terminal",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In", Direction = "input", Description = "Displays text to the console." },
                    new WiringPin { Name = "Set_Text_Color", Direction = "input", Description = "Sets the text color." },
                    new WiringPin { Name = "Clear_Text", Direction = "input", Description = "Clears the text." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "Outputs text typed on the console." },
                }
            },
            ["textdisplay"] = new WiringPanelInfo
            {
                Key = "textdisplay",
                Title = "Text Display",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "SET_TEXT", Direction = "input", Description = "Displays text to the screen." },
                    new WiringPin { Name = "SET_COLOR", Direction = "input", Description = "Sets the background color" },
                    new WiringPin { Name = "SET_TEXT_COLOR", Direction = "input", Description = "Sets the text color" },
                }
            },
            ["turrethardpoint"] = new WiringPanelInfo
            {
                Key = "turrethardpoint",
                Title = "Turret Hardpoint",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Power_In", Direction = "input", Description = "Power for firing the weapon once installed." },
                    new WiringPin { Name = "Position_In", Direction = "input", Description = "Sets the firing angle of the weapon once installed (0-360)." },
                    new WiringPin { Name = "Trigger_In", Direction = "input", Description = "Fires the weapon when it receives a signal." },
                    new WiringPin { Name = "Toggle_Light", Direction = "input", Description = "Toggles the state of the weapon's light." },
                    new WiringPin { Name = "Set_Light", Direction = "input", Description = "Sets the state of the weapon's light." },
                }
            },
            ["waterdetector"] = new WiringPanelInfo
            {
                Key = "waterdetector",
                Title = "Water Detector",
                Summary = "",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "Outputs a signal of 1 when water is detected, otherwise outputs 0." },
                    new WiringPin { Name = "Water_%", Direction = "output", Description = "Outputs the detector's room water level in %." },
                    new WiringPin { Name = "High_Pressure", Direction = "output", Description = "Outputs a signal of 1 when the room is under high pressure, otherwise 0." },
                }
            },
            ["wificomponent"] = new WiringPanelInfo
            {
                Key = "wificomponent",
                Title = "Wifi Component",
                Summary = "Allows remote communication between other wifi components that are using the same channel.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In", Direction = "input", Description = "The signal to be transmitted." },
                    new WiringPin { Name = "Set_Channel", Direction = "input", Description = "Sets the current wifi channel." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "The recieved signal." },
                }
            },
            ["xorcomponent"] = new WiringPanelInfo
            {
                Key = "xorcomponent",
                Title = "Xor Component",
                Summary = "Sends a signal if either of the inputs, but not both, receives a signal.",
                Pins = new WiringPin[]
                {
                    new WiringPin { Name = "Signal_In_1", Direction = "input", Description = "The input of the first signal." },
                    new WiringPin { Name = "Signal_In_2", Direction = "input", Description = "The input of the second signal." },
                    new WiringPin { Name = "Set_Output", Direction = "input", Description = "Sets the \"true\" output." },
                    new WiringPin { Name = "Signal_Out", Direction = "output", Description = "The output of the component." },
                }
            },
        };
    }

    private static IReadOnlyDictionary<string, string> CreateAliases()
    {
        return new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["aliendoor"] = "aliendoorshatches",
            ["aliendoorheavy"] = "aliendoorshatches",
            ["aliendoorsmall"] = "aliendoorshatches",
            ["aliendoorsmallwbuttons"] = "aliendoorshatches",
            ["aliendoorwbuttons"] = "aliendoorshatches",
            ["aliengeneratornew"] = "aliengenerator",
            ["alienhatch"] = "aliendoorshatches",
            ["alienhatchheavy"] = "aliendoorshatches",
            ["alienhatchsmall"] = "aliendoorshatches",
            ["alienhatchsmallwbuttons"] = "aliendoorshatches",
            ["alienhatchwbuttons"] = "aliendoorshatches",
            ["alienlightcomponent"] = "lightcomponent",
            ["alienterminal2"] = "alienterminal",
            ["alienterminalnew"] = "alienterminal",
            ["alienturretnew"] = "alienturret",
            ["blankperiscope"] = "periscope",
            ["concatcomponent"] = "concatenationcomponent",
            ["deconstructor"] = "fabricatordeconstructor",
            ["demultiplexercomponent"] = "outputselectorcomponent",
            ["dischargecoil"] = "electricaldischargecoil",
            ["dockinghatch"] = "dockinghatchport",
            ["dockinghatchwrecked"] = "dockinghatchport",
            ["dockingport"] = "dockinghatchport",
            ["dockingportwrecked"] = "dockinghatchport",
            ["door"] = "doorshatches",
            ["doorwbuttons"] = "doorshatches",
            ["doorwbuttonswrecked"] = "doorshatches",
            ["doorwrecked"] = "doorshatches",
            ["emergencylight"] = "lightcomponent",
            ["endruinheavydoorhorizontal"] = "aliendoorshatches",
            ["endruinheavydoorvertical"] = "aliendoorshatches",
            ["engine"] = "engines",
            ["exponentationcomponent"] = "exponentiationcomponent",
            ["fabricator"] = "fabricatordeconstructor",
            ["flakcannon"] = "flakcannonloader",
            ["guardianpodtrap"] = "guardianpod",
            ["hatch"] = "doorshatches",
            ["hatchwbuttons"] = "doorshatches",
            ["hatchwbuttonswrecked"] = "doorshatches",
            ["hatchwrecked"] = "doorshatches",
            ["junctionboxtutorial"] = "junctionbox",
            ["lamp"] = "lightcomponent",
            ["largeengine"] = "engines",
            ["lightcomponent90"] = "lightcomponent",
            ["lightcomponentround"] = "lightcomponent",
            ["lightfluorescentl01"] = "lightcomponent",
            ["lightfluorescentl01wrecked"] = "lightcomponent",
            ["lightfluorescentl02"] = "lightcomponent",
            ["lightfluorescentl02wrecked"] = "lightcomponent",
            ["lightfluorescentm01"] = "lightcomponent",
            ["lightfluorescentm01wrecked"] = "lightcomponent",
            ["lightfluorescentm02"] = "lightcomponent",
            ["lightfluorescentm02wrecked"] = "lightcomponent",
            ["lightfluorescentm03"] = "lightcomponent",
            ["lightfluorescentm03wrecked"] = "lightcomponent",
            ["lightfluorescentm04"] = "lightcomponent",
            ["lightfluorescentm04wrecked"] = "lightcomponent",
            ["lighthalogenm04"] = "lightcomponent",
            ["lighthalogenm04wrecked"] = "lightcomponent",
            ["lighthalogenmm01"] = "lightcomponent",
            ["lighthalogenmm01wrecked"] = "lightcomponent",
            ["lighthalogenmm02"] = "lightcomponent",
            ["lighthalogenmm02wrecked"] = "lightcomponent",
            ["lighthalogenmm03"] = "lightcomponent",
            ["lighthalogenmm03wrecked"] = "lightcomponent",
            ["lightleds01"] = "lightcomponent",
            ["lightleds01wrecked"] = "lightcomponent",
            ["multiplexercomponent"] = "inputselectorcomponent",
            ["navterminal"] = "navigationterminal",
            ["opresearchterminal"] = "researchstation",
            ["oscillator"] = "oscillatorcomponent",
            ["outpostoxygenerator"] = "oxygengenerator",
            ["outpostreactor"] = "nuclearreactor",
            ["outpostterminal"] = "terminal",
            ["oxygenerator"] = "oxygengenerator",
            ["powcomponent"] = "exponentiationcomponent",
            ["pump"] = "pumps",
            ["railguncontroller"] = "periscope",
            ["railgunloadersmall"] = "railgunloader",
            ["reactor1"] = "nuclearreactor",
            ["rearrailguncontroller"] = "periscope",
            ["regexcomponent"] = "regexfindcomponent",
            ["shuttlebattery"] = "battery",
            ["shuttleengine"] = "engines",
            ["shuttlenavterminal"] = "navigationterminal",
            ["shuttleoxygenerator"] = "oxygengenerator",
            ["smalldoor"] = "doorshatches",
            ["smallpump"] = "pumps",
            ["streetlight"] = "lightcomponent",
            ["timeddetonator"] = "detonator",
            ["valve"] = "pipevalve",
            ["windoweddoor"] = "doorshatches",
            ["windoweddoorwbuttons"] = "doorshatches",
            ["windoweddoorwbuttonswrecked"] = "doorshatches",
            ["windoweddoorwrecked"] = "doorshatches",
        };
    }
}
